### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jaschdoc** [jaschdoc/flix-develop#1]
**Must**
- [x] https://github.com/flix/flix/issues/2028
- Write tests that observe overload of effects (see map fusion test)
- Refactor `memberOf` to use `exists`
- [x] https://github.com/flix/flix/issues/2073
- [x] https://github.com/flix/flix/issues/2033

More info: https://github.com/flix/flix/issues/2059
https://github.com/flix/flix/issues/2076

**Should**
- [x] https://github.com/flix/flix/issues/2062 - Rename functions `funName_TODO` until implemented, add signatures and Flixdoc.
- [x] https://github.com/flix/flix/issues/2040 - Rename functions `funName_TODO` until implemented, add signatures and Flixdoc.
